### ISSUE TITLE
Spawning in others houses 

### ISSUE THREAD

**Issue by throw4w4y** [Uuvana-Studios/longvinter-windows-client#1057]
I was playing the game actively during the 1.0.7b version on Uuvana 6. I made a house and fully upgraded it except for the interior upgrade with 100 wood. After a few weeks the new updates came out, and I hopped on to see what the game was like. To preface this when I got off last I was in my home. When I loaded in I was inside someone else's house; I could access all the chests and I could use the workbench. I was able to even change the house's code. I ended up changing the codes to my own, and after I left the house I had to input the code for the door. The code I changed it to work, but I couldn't open gates(I could remove them though). I'm not gonna say my name or have screenshots; because, the person whose house I spawned in had signs with homophobic slurs around their house. This should definitely be fixed though.

**Comment by faketucker** [comment]
When your house decays, someone may build a new house in the same spot, so that when you return, you spawn in their house. We should add some functions to check if the player is in the house and teleport the player to a safe zone if the house has already decayed. Nobody should be able to change the house code unless they are the owner.

**Comment by Jalsson** [comment]
We added a fix for this where when your house decays it resets your respawn point to the Sgt. lake
