### ISSUE TITLE
Fence and house disappearance, and initialization of house upgrades

### ISSUE THREAD

**Issue by JK6619** [Uuvana-Studios/longvinter-windows-client#1097]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Divecchio** [comment]
Describe the bug
A clear and concise description of what the bug is.

The update, from the second floor has bug my chests and my friend's house has disappeared

*There should be another cleanup on all servers

*half of the server has this error next to the fences

My server is Europa Number 2

Sorry my english so bad

To Reproduce
Steps to reproduce the behavior:

Go to '...'
Click on '....'
Scroll down to '....'
See an error
Expected behavior
A clear and concise description of what you expected to happen.

Screenshots
If applicable, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/110181249/181528150-151ee86f-3367-4b85-a362-7e06a9aacda2.png)

![image](https://user-images.githubusercontent.com/110181249/181535722-1466bc85-2d69-441c-a9c5-a8c57b68f158.png)
![image](https://user-images.githubusercontent.com/110181249/181540038-ba997c94-2bbb-40c1-9f07-14022ee6dc64.png)


Desktop (please complete the following information):

OS: [e.g. Windows]
Game Version [e.g. 1.0]
Steam Version 7.39
Additional context
Add any other context about the problem here.

**Comment by biffotmc** [comment]
copy of #1094
