### ISSUE TITLE
New house update bug, stuff stuck behind the wall

### ISSUE THREAD

**Issue by Rosyleelee** [Uuvana-Studios/longvinter-windows-client#1099]
My cabinets are stuck behind the wall and windows, I lost all of my items because of this. 
Please fix this issue.
![20220728_230233](https://user-images.githubusercontent.com/110181171/181528975-43ea5ca2-616f-4453-ad61-2fa44b577122.jpg)

**Comment by wdefsdfwfd** [comment]
후..

**Comment by Ediaz1003** [comment]
I'm having the same issue I lost my cabinet full of guns and a work bench.

**Comment by Ediaz1003** [comment]
I also can't even go upstairs.

**Comment by heehehe1** [comment]
![image](https://user-images.githubusercontent.com/110182764/181576102-1ccb493b-0496-44e7-807a-572938870072.png)

**Comment by MineMy** [comment]
Checked. It's happen when there is not enough space around when upgrading the house.
In the 2nd hotfix, we forced a lot of players' homes to upgrade, and I believe this was caused by a lack of space around a lot of players' homes.

This message written by ruby star on discord may be helpful.
---------------- Original Messages ----------------
안녕하세요, 이번 1.0.8b 패치 이후로 집 면적이 갑자기 좁아져서 캐비넷박스들이 집 영역 밖에 보이는 이슈가 있습니다. [1번 째 이미지]
Hello, after this 1.0.8b update, area of the house suddenly narrowed, so there is an issue where cabinet boxes can be seen outside the area of the house. [look at first image below]
![](https://cdn.discordapp.com/attachments/955711547269853214/1002230086692519987/unknown.png)

해당 문제를 해결하는 법은 작업대에서 Second Floor 을 업데이트하면 집 영역이 확장됩니다. [하단 2번 째 이미지]
to solve problem, you have to upgrade house Second Floor from Workbench. [look at second image below]
then, it would be expanded.
![](https://cdn.discordapp.com/attachments/955711547269853214/1002230087179063476/unknown.png)

다만 주의할 점은 집 내부 확장 전(Second Floor 업그레이드)에 야외의 공간이 충분히 확보되어야 하는 점 참고 부탁드립니다.
야외 영역 공간이 확보가 되지 않으면 Second Floor로 업그레이드가 안됩니다. [하단 3번 째 이미지]
However, please note that enough outdoor space should be secured before the expansion of the house (= upgrade second floor).
If you have space with blocked(beside of house) or not enough outdoor space, you can't upgrade to the Second Floor. [look at 3rd image below] 
![](https://cdn.discordapp.com/attachments/955711547269853214/1002230087648804954/unknown.png)

**Comment by kbs4674** [comment]
@heehehe1 
Hello, please read this discord chat.
you can see find solve problem.

안녕하세요, 해당 문제는 https://discord.com/channels/846308806870695967/955711547269853214/1002230089766932560 글을 참고 부탁드립니다.


@Rosyleelee 
OMG...

**Comment by kbs4674** [comment]
Related issue from @MineMy :

만약 작업대에서 아래와같은 화면으로 보이면서 업그레이드가 안될경우... 이건 집 업그레이드 버그이슈라서.. 집을 철거했다가 다시 지어야 할 듯 합니다..
If you see the screen below on the workbench and cannot upgrade... This is a workbench bug issue.
you would be have to decay and rebuild it. 

![image](https://user-images.githubusercontent.com/19690475/181577802-86730bbd-7586-4065-a5c5-bc591bd14721.png)

**Comment by Sillvvvv** [comment]
Items stuck in walls and it says 2nd floor upgrade is installed but it's not, tried removing the fences around my house and reboot but house didn't upgrade. :(

![image](https://user-images.githubusercontent.com/109499358/181584492-a4f54f23-ff86-4b7a-a36c-29adc927e27f.png)

![image](https://user-images.githubusercontent.com/109499358/181584519-693a8dde-f2dc-48eb-bc7c-56ea1eb87a20.png)

![image](https://user-images.githubusercontent.com/109499358/181584554-01ef0291-dda2-4c83-b745-e1967156617d.png)

**Comment by ruler76** [comment]
![1659023522074](https://user-images.githubusercontent.com/110187611/181584335-1341d5ac-7c40-4fe5-9d24-f74fee405241.jpg)
![1659023523779](https://user-images.githubusercontent.com/110187611/181584353-2b052e2b-fcb7-4e4a-84f0-3f255238d96b.jpg)

a phenomenon in which a house is not upgraded
There's plenty of room

**Comment by Sillvvvv** [comment]
> ![1659023522074](https://user-images.githubusercontent.com/110187611/181584335-1341d5ac-7c40-4fe5-9d24-f74fee405241.jpg) ![1659023523779](https://user-images.githubusercontent.com/110187611/181584353-2b052e2b-fcb7-4e4a-84f0-3f255238d96b.jpg)
> 
> a phenomenon in which a house is not upgraded There's plenty of room

we have the same problem :(

**Comment by kbs4674** [comment]
@Sillvvvv 
Actually, the `Second Floor` house has not been upgraded, but it seems bug that the `Secod floor` installed.
it might be decay & re-build house.

실제로 2층집이 업그레이드 되지 않았으나, 2층집이 설치된 상태로 있는것도 하나의 버그 같습니다..
저런경우에도 집을 다시 설치해야 할 듯 합니다...
