### ISSUE TITLE
bug second floor instaled. bug from update.

### ISSUE THREAD

**Issue by dimancorporation** [Uuvana-Studios/longvinter-windows-client#1101]
where is my second floor?
house became much narrower

![s1](https://user-images.githubusercontent.com/69962198/181530231-a6aef0b8-d8ba-4430-bf16-5183adf31053.png)
![s2](https://user-images.githubusercontent.com/69962198/181530268-c9991b83-4454-4479-8896-6ffb2b0aade8.png)

**Comment by biffotmc** [comment]
copy of #1099

**Comment by MineMy** [comment]
Checked. It's happen when there is not enough space around when upgrading the house.
In the 2nd hotfix, we forced a lot of players' homes to upgrade, and I believe this was caused by a lack of space around a lot of players' homes.

This message written by ruby star on discord may be helpful.
---------------- Original Messages ----------------
안녕하세요, 이번 1.0.8b 패치 이후로 집 면적이 갑자기 좁아져서 캐비넷박스들이 집 영역 밖에 보이는 이슈가 있습니다. [1번 째 이미지]
Hello, after this 1.0.8b update, area of the house suddenly narrowed, so there is an issue where cabinet boxes can be seen outside the area of the house. [look at first image below]
![](https://cdn.discordapp.com/attachments/955711547269853214/1002230086692519987/unknown.png)

해당 문제를 해결하는 법은 작업대에서 Second Floor 을 업데이트하면 집 영역이 확장됩니다. [하단 2번 째 이미지]
to solve problem, you have to upgrade house Second Floor from Workbench. [look at second image below]
then, it would be expanded.
![](https://cdn.discordapp.com/attachments/955711547269853214/1002230087179063476/unknown.png)

다만 주의할 점은 집 내부 확장 전(Second Floor 업그레이드)에 야외의 공간이 충분히 확보되어야 하는 점 참고 부탁드립니다.
야외 영역 공간이 확보가 되지 않으면 Second Floor로 업그레이드가 안됩니다. [하단 3번 째 이미지]
However, please note that enough outdoor space should be secured before the expansion of the house (= upgrade second floor).
If you have space with blocked(beside of house) or not enough outdoor space, you can't upgrade to the Second Floor. [look at 3rd image below] 
![](https://cdn.discordapp.com/attachments/955711547269853214/1002230087648804954/unknown.png)
