### ISSUE TITLE
Inactivity removal 

### ISSUE THREAD

**Issue by amorrenicole** [Uuvana-Studios/longvinter-windows-client#116]
**Is your feature request related to a problem? Please describe.**
I would like to recommend  inactivity removal.
I played this game since day one and since it was pretty much empty people only placed their tents randomly and never again showed up. So I have neighbours who never play and new people coming to the server have no place to put up their tents. And I do play this game constantly right now, I know for a fact that these people never showed up again.

**Describe the solution you'd like**
I would set it to 10 days.
So that people get the chance to play if they only have the time to on weekends. People who really want to play can just add a little to their base to keep the activity timer up but those who have not touched their tents should definitely be removed.
More and more people are joining but the capacity just isn't there.

**Comment by aaaaaaaaaaaavm** [comment]
I have been guilty of abandoning my house. But that was because I was constantly being robbed of my produce from every passer-by and because I placed my house too close to the water and was unable to use a lot of space. 

A way they could improve upon this would be an ability to move your house or maybe just being able to chop the whole thing down and everything is converted into a drop of a tent and a couple of bags of wood, as it was previously.

**Comment by faketucker** [comment]
Tent decay is now implemented in the game.
