### ISSUE TITLE
watter

### ISSUE THREAD

**Issue by AJIbPHA** [Uuvana-Studios/longvinter-windows-client#1199]
Wtf?
![image](https://user-images.githubusercontent.com/111048398/187252692-fd7b8236-6bac-4af6-90a3-1c2b7b4c349c.png)

**Comment by BonesIsLive** [comment]
Please file a proper report and indicate what those coordinates are so we can further check if it was just a client side error or a map bug

**Comment by AJIbPHA** [comment]
@Please file a proper report@
where i can take this?

**Comment by BonesIsLive** [comment]
fill up the following information:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See an error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**
Add any other context about the problem here.

**Comment by AJIbPHA** [comment]
its are coordinats 
![2022-09-01 (4)](https://user-images.githubusercontent.com/111048398/187951828-1a73751d-cb2f-499e-a0d7-42623e666187.png)

**Comment by faketucker** [comment]
Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible.
