### ISSUE TITLE
Progress gets reset when joining server

### ISSUE THREAD

**Issue by Juareza497** [Uuvana-Studios/longvinter-windows-client#120]
**Describe the bug**
When I joined the server I play on, Uuvana 5, spawn at a starting port with no items. All of my progress with fishing, farming, etc. also gets reset. I also lost all of the money I had.

**To Reproduce**
1. just join the server

**Expected behavior**
Join the server where I left off and have my items, money, and progress. 

**Screenshots**
![Capture](https://user-images.githubusercontent.com/90014311/156223955-c180f2b6-9b8c-4809-b75a-72d3c0ccbf0d.PNG)
![Capture2](https://user-images.githubusercontent.com/90014311/156223959-32f65645-8b54-4b88-a89b-5fea444852a3.PNG)

**Desktop (please complete the following information):**
 - OS: windows 10
 - Game Version [1.0.0]
 - Steam Version API v020  packet version: 1642451672

**Additional context**

**Comment by sirNugg3ts** [comment]
Just tested this and it does reset in fact

**Comment by shaggy859** [comment]
happened to me on uuvana 2

**Comment by Foxxguy** [comment]
This has happened to me twice now on uuvana 2.

**Comment by mrccwolf** [comment]
This just happened to be on uuvana 7. Normally I can leave and re-join without issues. After spending 2 days on the server I was hanging with some people at a safe zone when one of them said "do it" and next thing I know I was disconnected from the server. Maybe wipes are related to a crash or unexpected disconnect? Was I targeted and booted from the server? Maybe it was a coincidence. My house and all contents were still in the boxes, but money, progress, and anything on my person was reset and I was returned to the default spawn location.

**Comment by mrccwolf** [comment]
This seems to be related to steam updates / server updates. I notice that both times (tonight) I had steam updates for the game. Both times were sudden disconnects from the server. Only one of them wiped my character.

**Comment by yoshasudungan** [comment]
hi this thing happened on me on [SINGAPORE] uuvanA

what happened is 

1. i want to place the turret
2. while placing the turrent i die (because of losing energy on  the cold region)
3. then i die and somehow my turret is stuck (like it was only have green color like when we try to place the turret)
4. i tried to relog-in 
5. tada all the item gone

either that or when i try to login i do see that the number of player per server is actually maxed out

**Comment by Tenacle** [comment]
Happened in Uuvana 7. Lost all compendium and inventory and location data. I still have access to friends property.
What happened:
1. Had a window stuck on my face at safe zone and had to restart
2. Joined again and was teleported to a starting safe zone with no items or compendium.
3. Repeated joins starts me at 2.

**Comment by shh1n** [comment]
I have the same problem on (uuvana 3 EU). Hope it gets fixed quickly.

**Comment by Neylick** [comment]
I have encountered the same problem (twice) on uuvana 3 EU, I still have my house tho. Compendium, inventory and credits get reset, but the house is still there with everything in place. I also get transported back to the default spawn.

This bug is also inconsistent because I managed to reconnect multiple times without having that issue. Most of the times, if I reconnect quickly, I don't get any problems but if I reconnect after a good night of sleep everything disapeared. Don't know if that's just luck or if the server forgets about you after a while, maybe because of a cleaning procedure or players connected in the meantime, making the server forget about older players ?

Good luck fixing this, if you need logs please let me know

**Comment by shh1n** [comment]
unfortunately it doesn't work for me yet.

**Comment by Jalsson** [comment]
Newest update moved all the player information to one file wich is loaded on server startup and saved every 6 minutes. This should make joining and loading your character much more reliable.
