### ISSUE TITLE
Camera Rotation

### ISSUE THREAD

**Issue by MrVilo** [Uuvana-Studios/longvinter-windows-client#234]
I think a camera rotation feature would be really good as a feature for this game as when it comes to building and farming and collecting items/blocks behind trees/buildings there are always obstacles on your way on building, farming even collecting items. I think with this feature it would help a lot of players who are frustrated not being able to build fully on how they want to build, without this feature I believe players would agree with me on this when I say we just have to compromise by building around what we cannot build i.e.: behind the house or stacked object.

I hope this feature would be added to the game, as it would help a lot of players.

Thank you for all your hard work!!
-MrVilo

**Comment by TheJudeAbides** [comment]
Nothing worse than shooting a bird right beside a north-facing cliff, and because of perspective you cant get to the loot to pick it up. def needs either a rotation feature or when your character is behind something, the terrain in front of them becomes translucent so you can see through it, and select items behind it. Another ISO game, Project Zomboid, takes this approach.

**Comment by Bunnbunnnn** [comment]
Documented on forum as 
-More camera rotation ability / zoom options
