### ISSUE TITLE
free box fix please

### ISSUE THREAD

**Issue by qoginiii** [Uuvana-Studios/longvinter-windows-client#352]
hey! I found a bug where when you're in the safe zone your box won't spawn. and bounce together at one point and when someone builds a house there He gets free stuff all the time from people who use the safe zone.

**Comment by faketucker** [comment]
I believe this is the bug where someone dies, their bag becomes crates, and it's already fixed.

Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. Next time, please use the appropriate template that we provided.
