### ISSUE TITLE
Cheating Death and dupe items in the process (Extremely urgent to fix!)

### ISSUE THREAD

**Issue by drawesometoons** [Uuvana-Studios/longvinter-windows-client#361]
Hello!
You can cheat death by simply Alt-F4 right when you die ingame. It will reset your character to the last saved location with intact backpack.
With help this has the potential of duping things:
If you get killed by a friend with an inventory full of wood for example
Alt-F4 you will respawn with your inventory still full
while your friend can also loot your full inventory. Duplicating the inventory.

The game has to do a save in the instant the character is at 0 health. 

I love the game so far!

**Comment by Dodg-e** [comment]
Can confirm whole inventory can be duped, dont even need someone to kill you can just use a fire then alt+f4, it's caused by player save issues, a solution would be to not instantly make the character disappear when quitting the game or disconnecting and instead having the character stay in the world for 5-10 seconds, check if there's still no response from client then save player data and remove character, it would also solve the issues with combat logging at the same time.

**Comment by faketucker** [comment]
[Fixed](https://discord.com/channels/846308806870695967/946785267984003072/953314228251557898)

**Comment by drawesometoons** [comment]
If it was fixed with this update its still working.

**Comment by faketucker** [comment]
The latest update is doable again, but it's rolled back further.
