### ISSUE TITLE
Missing box in my house

### ISSUE THREAD

**Issue by SoGameuse** [Uuvana-Studios/longvinter-windows-client#431]
Hi everyone, 

I've had a small issue with the game today. I thought our houses were safe places so here I am with an issue. I had 3 boxes on top of each other and when I reconnected on to the server later on, one of my boxes were missing.

Before (at 12 noon today)
![avant](https://user-images.githubusercontent.com/101669700/158458431-296654bb-9fc4-4641-b4b6-7c72495fb23a.png)
After (at half 8 tonight)
![apres](https://user-images.githubusercontent.com/101669700/158458532-48b242d2-b3b7-4fa4-aa80-b1c3296f2678.png)

Between the 2, a neighbour has put down a tent not far away. I don't know if that has anything to do with it. 

Thanks for your help :)

**Comment by xZephlin** [comment]
Same thing happened to me. lost two containers, whole inventory (and mK) was gone, as well as my compendium.

**Comment by sirNugg3ts** [comment]
From FAQ

I just lost my progress / my inventory (or house) disappeared, I want my stuff back!
- We are aware of the time some of you are putting on our game, and we are thankful.
Still we are, as you should be aware, in EA and Beta, which means a lot of updates might delete stuff that might have been done until that point, creating partial or full wipes.
At the moment there's nothing we can do until the game is somewhat stable, we ask for your comprehension and patience while we work on your next favorite game ❤️

This might also be due to the saving only guranteeing saves every 15 min more or less. This might have happened when the server went to update and didn't store everything you did in that time frame
