### ISSUE TITLE
cant access server

### ISSUE THREAD

**Issue by theTotalbroski3** [Uuvana-Studios/longvinter-windows-client#438]
i got this game about two weeks ago and it has worked fine except that the water texture wasnt there but i didnt really care. but when i went to logon to this server one day, it loaded for about 10 seconds then put me back to the main screen without telling me any errors at all. i tried loading in to a different server and it worked just fine but for this specific server it no longer lets me in and gives no information about why i cant get in. i tried restarting my computer. i tried verifiying the games integrity, and then finally uninstalling and reinstalling the game but it still doesnt work. please help me i really like this game.

**Comment by tsukasaroot** [comment]
Like you can get into other servers, its mosr likely this particular server's ownee that didn' t updated his server, you'll have to wait for him to do so.

**Comment by sirNugg3ts** [comment]
1st issue: 
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.

2nd issue: as @tsukasaroot the odds of this being on an official server are very low. If it is, open a bug report with the correct details
