### ISSUE TITLE
My house is gone, but other houses in the same server are still there :( Right after the last update. Only firepits were left. 

### ISSUE THREAD

**Issue by poonuood** [Uuvana-Studios/longvinter-windows-client#470]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.

Also the house was mostly built when the saving system wasn't updating the save, which means the last 15 min more or less were deleted

Please read our FAQ on discord too
