### ISSUE TITLE
STUCK IN WATER - CAN'T PL.AY

### ISSUE THREAD

**Issue by Leesa2594** [Uuvana-Studios/longvinter-windows-client#479]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by Leesa2594** [comment]
I was crossing the water and then it bugged out, went to home screen and now when I log back in I am in the water and cannot move

**Comment by Leesa2594** [comment]
I am on the usana 5 server

**Comment by silvesty20** [comment]
Sorry to tell yah, but just die in the game is currently the only way. I also had this 2 time's. RIP

**Comment by sirNugg3ts** [comment]
1st 
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.

2nd please read faq on discord, right now there is not much we can do while we update the game
