### ISSUE TITLE
REGARDING HACKERS

### ISSUE THREAD

**Issue by ZELDACHIK64** [Uuvana-Studios/longvinter-windows-client#487]
I HAVE PLAYED ON SEVERAL SERVERS TO GET A FEEL FOR THE GAME AND THERE IS A SERVER LAST NIGHT CALLED BACONLIFE US EAST, ITS ROUGHLY 100 PLAYERS, BUT HAS ANYWHERE FROM 5-20 PLAYERS ACTIVE AT ALL TIMES. LAST NIGHT I REFUSED TO JOIN A CLAN ON THE SERVER AND DID NOT CATCH THEIR NAMES, BUT THIS MORNING WHEN I LOGGED ON MY HOUSE AND ALL MY ITEMS WERE GONE. I WALKED AROUND THE ENTIRE MAP AND EVERYONES HOMES WERE STILL INTACT. I EVEN ASKED AROUND. I WAS TOLD THERE IS A HACKER ON THIS SERVER IF I DONT DO WHAT THEY ASK. THIS NEEDS TO BE ADDRESSED. I AM NOT SURE HOW MANY SERVERS HAVE HACKERS, BUT THIS IS GOING TO RUIN THE GAMEPLAY FOR PEOPLE STARTING OUT WANTING TO HAVE A GOOD TIME. SORRY TO BRING THIS UP, BUT I CAN SEE IT BEING AN ISSUE IN THE FUTURE. ESPECIALLY IF PEOPLE PUT IN DAYS OF WORK. THANKS.

**Comment by biffotmc** [comment]
This is not an official server you are talking about, we are actively trying to fix the hacker problem, but as of now all you can do is wait/contact the owner of the server you were on.

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.

Also just caps will make just close the issue and not even read what you wrote. This is not a place to complain about the state of the game, its a place to file bugs so that we can work on them
