### ISSUE TITLE
Getting stuck in houses and containers unable to move even with no items in it!

### ISSUE THREAD

**Issue by Rez25** [Uuvana-Studios/longvinter-windows-client#528]
**Describe the bug**
I've been continuously getting stuck in houses with no way out until I dc and rejoin. Also my containers are empty and i try to pick them up to move and it won't even allow me to pick up the empty container. I have also encountered frame drops around turrets. Pls help!

**Comment by unknownLinguist** [comment]
Dunno about getting stuck in the houses, but I have also experienced the not able to pick up containers glitch.  In fact it resulted in a duplication glitch for me!

**Comment by faketucker** [comment]
Can you leave your house now? I need more info about that. If you know an exact way to replicate it, feel free to reopen this issue again.

And the container bug occurred because two containers were placed in the same spot and should be fixed by the latest update; you can no longer place two items in the same spot anymore. You should be able to pick it up after the server restarts.
