### ISSUE TITLE
상점에 들어가고 마우스 키를 누르면 메뉴 화면이 나옵니다

### ISSUE THREAD

**Issue by ysm5639** [Uuvana-Studios/longvinter-windows-client#676]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible. It would help us a lot if you could provide us with a screenshot or a video.
