### ISSUE TITLE
갑자기 텐트가 없어지고 텐트 안에있던 아이템이 없어집니다

### ISSUE THREAD

**Issue by Baejihoon02** [Uuvana-Studios/longvinter-windows-client#682]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Please use English here. Bug reports that are not filled in correctly will not be taken into consideration since we need steps to replicate the bugs or we have no way to fix them. If you want to report the bug, fill in as much information as possible. It would help us a lot if you could provide us with a screenshot or a video.
