### ISSUE TITLE
why does my house keep disappearing not a server wipe its happen 2 times since the wipe lose all my mats and house

### ISSUE THREAD

**Issue by picklefritz375** [Uuvana-Studios/longvinter-windows-client#845]
*wth 2 times in the last 2 day s i spent 3 hours building my house and collecting resources just to log out and come back a hour later and my house and all my stuff are gone 2 times not an early access problem its a wth problem' most early access games i played done wipe active players on a server wipe seems to be a huge issue here' but this was not a server wipe issue.

**Comment by sirNugg3ts** [comment]
Bug reports that are not filled correctly will not be taken in consideration, since we need steps to replicate the bugs or we have no way to fix them.
Please create a new bug report with the appropriate template.
Also you must tell us in which server you are in. If this is happening on a non-official server there is no way for us to guarantee that the server setup is done correctly
