### ISSUE TITLE
Update literally set me back to the past(money that i earned,things in the bag,lost all ).what happened with this update.

### ISSUE THREAD

**Issue by kevinan2** [Uuvana-Studios/longvinter-windows-client#917]
**Describe the bug**

**To Reproduce**
4. See an error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Game Version [e.g. 1.0]
 - Steam Version [e.g. 1.0]

**Additional context**

**Comment by faketucker** [comment]
Unfortunately, we cannot assist players in restoring their in-game stuff since this occurred because the server files may not have been saved correctly or may have become corrupted in some way while we're updating the server, and the devs are working to resolve this as they improved the saving system in the last update. We would appreciate your understanding and patience
