### ISSUE TITLE
Can't join any server

### ISSUE THREAD

**Issue by SunFoxx** [Uuvana-Studios/longvinter-windows-client#976]
After several seconds, I am being dropped back to the main menu each time I try to connect the server. Not received any messages or errors, just plainly opened main menu. If I try to connect the same server once again I'll be stuck at loading screen forever with only the possibility to exit via task manager. I tried it with different servers - reproduced each time.

**Desktop**
 - OS: Windows 10 (run with Parallels from MacOS)
 - Game Version: 1.0.7b
 - Steam package Version 1654574690

**Comment by faketucker** [comment]
Try to check your firewall and let the game pass through your firewall.

**Comment by kenpachi437** [comment]
I am having the same issue. Ever since the 1.0.8 update, I have not been able to enter any server. No reason was given it just kicks me out of the loading screen. When I try again it just loads forever. I have checked the firewall and it does not seem to be the issue. Or at least I did not see it as the issue. Maybe there is something I am missing. I have seen a few people with this issue, but no one has a fix yet.

**Comment by Minniix** [comment]
Unfortunately I have the same problem. I can't join a server or start my own :( unfortunately I have to return the game. It would be great if the problem is fixed, because I would like to report about it on my website.

**Comment by Exolight-OG** [comment]
I Have the same problem and the firewall has nothing to do with it.!
pls fix it....

**Comment by faketucker** [comment]
> I Have the same problem and the firewall has nothing to do with it.! pls fix it....

You're on a day ban because your bad behaviour, dude

**Comment by swamp2706** [comment]
même problème pour moi, cela fait 2 semaines je ne peux rejoindre aucun serveur, et donc jouer par la même occasion
